import Foundation
import LitheCoreContracts

typealias LanguageTestItemKind = LitheCoreContracts.LanguageTestItemKind
typealias LanguageTestItem = LitheCoreContracts.LanguageTestItem
typealias LanguageTestScope = LitheCoreContracts.LanguageTestScope
typealias LanguageTestContext = LitheCoreContracts.LanguageTestContext
typealias LanguageTestPlan = LitheCoreContracts.LanguageTestPlan
typealias LanguageTestResults = LitheCoreContracts.MavenTestResults
typealias LanguageTestFailureDetail = LitheCoreContracts.MavenTestFailureDetail
typealias LanguageTestProvider = LitheCoreContracts.LanguageTestProvider
